
version: '3.8'

services:
  app:
    build: .
    container_name: referat-app
    restart: always
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - VITE_SUPABASE_URL=https://whrpnqvnujhzqljjmxum.supabase.co
      - VITE_SUPABASE_ANON_KEY=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndocnBucXZudWpoenFsampteHVtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU1MzQyNjMsImV4cCI6MjA2MTExMDI2M30.DKZ5yPiR9RKOzSP65-Ba5ZYX-sLqJ9cXnsolb_Vntl8
    volumes:
      - ./:/app
      - /app/node_modules
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
